#!/usr/bin/env bash
set -o nounset
set -o pipefail

# GENERATED FROM iron-laws.yml — DO NOT EDIT
# Source version: 1.0.0 (updated 2026-03-22)

cat <<'EOF'
{"hookSpecificOutput":{"hookEventName":"SubagentStart","additionalContext":"Ruby/Rails/Grape Iron Laws (NON-NEGOTIABLE) — 21 Total:\n\nActive Record (7):\nSidekiq (4):\nSecurity (4):\nRuby (3):\nHotwire/Turbo (2):\nVerification (1):\n\nIron Law 1: NEVER use float for money — use decimal or integer cents\nIron Law 2: ALWAYS use parameterized queries — never SQL string interpolation\nIron Law 3: USE includes/preload for associations — never N+1 queries\nIron Law 4: IN Active Record code, use after_commit not after_save when enqueueing jobs\nIron Law 5: WRAP multi-step operations in ActiveRecord::Base.transaction\nIron Law 6: NO update_columns or save(validate: false) in normal flows\nIron Law 7: NO default_scope — use explicit named scopes only\nIron Law 8: Jobs MUST be idempotent — safe to retry\nIron Law 9: Args use JSON-safe types only — no symbols, no Ruby objects, no procs\nIron Law 10: NEVER store ORM objects in args — store IDs, not records\nIron Law 11: ALWAYS enqueue jobs after commit using the active ORM or transaction hook\nIron Law 12: NO eval with user input — code injection vulnerability\nIron Law 13: AUTHORIZE in EVERY controller action — do not trust before_action alone\nIron Law 14: NEVER use html_safe or raw with untrusted content — XSS vulnerability\nIron Law 15: NO SQL string concatenation — always use parameterized queries\nIron Law 16: NO method_missing without respond_to_missing? — breaks introspection\nIron Law 17: SUPERVISE ALL BACKGROUND PROCESSES — use proper process managers\nIron Law 18: DON'T RESCUE Exception — only rescue StandardError or specific classes\nIron Law 19: NEVER query DB in Turbo Stream responses — pre-compute everything\nIron Law 20: ALWAYS use turbo_frame_tag for partial updates\nIron Law 21: VERIFY BEFORE CLAIMING DONE — never say 'should work' — run tests and show results\n"}}
EOF
